# Generated by Django 3.2.7 on 2021-09-03 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desp',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='desp',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 23, 37, 42, 53622, tzinfo=utc)),
        ),
    ]
