# Generated by Django 3.2.7 on 2021-09-03 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0004_auto_20210903_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desp',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='desp',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='item',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 6, 10, 54, 194075, tzinfo=utc)),
        ),
    ]
